Item (Draft)
dueruen/4.-Semester-Project pull request #51
Opened 2019-05-14 08:03 UTC by GGkarma

2019-05-14 08:54 UTC, dueruen requested changes

2019-05-14 08:54 UTC, dueruen commented on RacingGame/CommonItem/src/main/assembly/felix.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This file is not needed

2019-05-19 20:25 UTC, dueruen approved these changes

2019-05-19 20:25 UTC, quartercastle approved these changes

2019-05-19 20:25 UTC, merged